### ISSUE TITLE
Not Working with SpringCypherRestGraphDatabase in spring-data-neo4j-rest

### ISSUE THREAD

**Issue by zhoujiagen** [zhoujiagen/SpringDataBasedNoSQLTutorials#3]
Try to play with Neo4j Server using maven dependency:

		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-neo4j-rest</artifactId>
			<version>3.3.2.RELEASE</version>
		</dependency>

and with configuration:

	public static final String SERVER_URL = "http://localhost:7474/db/data";

	@Bean
	public GraphDatabaseService graphDatabaseServiceWithError() {
		SpringCypherRestGraphDatabase result = new SpringCypherRestGraphDatabase(SERVER_URL, "neo4j", "root");
		return result;
	}

exception stack:

	java.lang.RuntimeException: Error adding element 19 className LineItem to index __rel_types__
		at org.neo4j.rest.graphdb.RestAPIImpl.addToIndex(RestAPIImpl.java:703)
		at org.neo4j.rest.graphdb.RestAPICypherImpl.addToIndex(RestAPICypherImpl.java:683)
		at org.neo4j.rest.graphdb.index.RestIndex.add(RestIndex.java:58)
	......
		at com.sun.proxy.$Proxy45.save(Unknown Source)
		at com.spike.springdata.neo4j.SpringDataBookWithRepositoryTest.populateGraph(SpringDataBookWithRepositoryTest.java:111)

**Comment by zhoujiagen** [comment]
Use deprecated `SpringRestGraphDatabase` instead:

	@Bean
	@Profile("PRODUCT")
	public GraphDatabaseService graphDatabaseService() {
		@SuppressWarnings("deprecation")
		SpringRestGraphDatabase result = new SpringRestGraphDatabase(SERVER_URL, "neo4j", "root");
		return result;
	}
